const $=s=>document.querySelector(s);
const C={family:$('#family'),severity:$('#severity'),start:$('#start'),duration:$('#duration'),bone:$('#bone'),brain:$('#brain'),persist:$('#persist'),iodine:$('#iodine'),multi:$('#multi'),generations:$('#generations')};
const REF={femur:434,icv:1341}, LB1={femur:280,icv:430};
const overlap=(start,dur,a,b)=>Math.max(0,Math.min(start+dur,b)-Math.max(start,a))/(b-a);
function multiState(E,g){let S=0,rho=.28,c=.18;for(let i=0;i<g;i++)S=rho*S+c*E*(1-S);return Math.max(0,Math.min(1,S))}
function calc(){
 const fam=C.family.value,se=+C.severity.value/100,bo=+C.bone.value/100,br=+C.brain.value/100,p=+C.persist.value/100,st=+C.start.value,du=+C.duration.value,iod=+C.iodine.value/100,m=+C.multi.value/100,g=+C.generations.value;
 const bf=Math.max(0,overlap(st,du,14,40)), cf=Math.max(0,overlap(st,du,20.5,34.5)), early=Math.max(0,overlap(st,du,4,20));
 let bl=0,cl=0,note='',S=0,sus=1,thyroid=0;
 if(fam==='uniform'){bl=cl=se;note='Uniform scaling reduces both selected endpoints by the same proportion.'}
 if(fam==='gc'){bl=.03*se*bf;cl=.04*se*cf;note='Glucocorticoid effects remain intentionally modest.'}
 if(fam==='fgr'){bl=se*Math.max(.35,bo)*bf*Math.min(.55,p);cl=se*Math.min(.40,br)*cf*Math.min(.45,p);note='Transient FGR emphasizes skeletal restriction with relative cranial sparing.'}
 if(fam==='igf'){let bc=Math.max(.55,bo),rc=Math.max(.25*bc,Math.min(.75*bc,br));bl=se*bc*bf*Math.max(.60,p);cl=se*rc*cf*Math.max(.45,p);note='Persistent IGF disturbance affects skeletal and cranial growth independently.'}
 if(fam==='iodine'){thyroid=iod*(.25+.75*se);let timing=Math.min(1,.7*early+.3*cf);cl=thyroid*(.3+.7*br)*timing*(.6+.4*p);bl=thyroid*(.35*bo)*bf*(.1+.6*p);note='Iodine–thyroid model weights early neural development more strongly than skeletal growth.'}
 if(fam==='combined'){S=multiState(m,g);sus=1+S*.5;thyroid=iod*(.25+.75*se);let timing=Math.min(1,.7*early+.3*cf);let ib=thyroid*(.35*bo)*bf*(.1+.6*p)*sus,ic=thyroid*(.3+.7*br)*timing*(.6+.4*p)*sus;let bc=Math.max(.55,bo),rc=Math.max(.25*bc,Math.min(.75*bc,br));let gb=se*bc*bf*Math.max(.6,p)*sus,gc=se*rc*cf*Math.max(.45,p)*sus;bl=1-(1-Math.min(.95,ib))*(1-Math.min(.95,gb));cl=1-(1-Math.min(.95,ic))*(1-Math.min(.95,gc));note=`${g} generations produce a vulnerability state of ${S.toFixed(2)}, modifying susceptibility to final-pregnancy iodine/thyroid and IGF perturbations.`}
 bl=Math.min(.95,Math.max(0,bl));cl=Math.min(.95,Math.max(0,cl));
 let fem=REF.femur*(1-bl),icv=REF.icv*(1-cl),d=((fem-280)/24)**2+((icv-430)/100)**2;
 return {fam,st,du,fem,icv,d,note,S,sus,thyroid};
}
function draw(x){const grid=$('#grid'),marks=$('#marks');let L=68,R=725,T=28,B=365,x0=150,x1=460,y0=250,y1=1450,sx=v=>L+(v-x0)/(x1-x0)*(R-L),sy=v=>B-(v-y0)/(y1-y0)*(B-T),g='';[200,250,300,350,400,450].forEach(v=>{let X=sx(v);g+=`<line x1="${X}" y1="${T}" x2="${X}" y2="${B}" stroke="#83b8d1" stroke-opacity=".15"/><text x="${X}" y="394" fill="#6f8997" font-size="11" text-anchor="middle">${v}</text>`});[400,600,800,1000,1200,1400].forEach(v=>{let Y=sy(v);g+=`<line x1="${L}" y1="${Y}" x2="${R}" y2="${Y}" stroke="#83b8d1" stroke-opacity=".15"/><text x="53" y="${Y+4}" fill="#6f8997" font-size="11" text-anchor="end">${v}</text>`});g+=`<text x="397" y="420" fill="#8aa6b5" font-size="12" text-anchor="middle">Femur length (mm)</text><text x="17" y="196" fill="#8aa6b5" font-size="12" text-anchor="middle" transform="rotate(-90 17 196)">Endocranial volume (cc)</text>`;grid.innerHTML=g;let pts=[[434,1341,'#748b97',8,'Reference'],[280,430,'#f49b4b',10,'LB1'],[x.fem,x.icv,'#70d0ff',11,'Current model']];marks.innerHTML=pts.map(p=>`<circle cx="${sx(p[0])}" cy="${sy(p[1])}" r="${p[3]+6}" fill="${p[2]}" opacity=".08"/><circle cx="${sx(p[0])}" cy="${sy(p[1])}" r="${p[3]}" fill="${p[2]}" stroke="white" stroke-opacity=".55"/><text x="${sx(p[0])+14}" y="${sy(p[1])-13}" fill="${p[2]}" font-size="11">${p[4]}</text>`).join('')}
function visibility(){let f=C.family.value,iod=f==='iodine'||f==='combined',mul=f==='combined';$('#iodineRow').classList.toggle('inactive',!iod);$('#multiRow').classList.toggle('inactive',!mul);$('#genRow').classList.toggle('inactive',!mul)}
function update(){let x=calc();$('#severityOut').textContent=C.severity.value+'%';$('#startOut').textContent=C.start.value+' weeks';$('#durationOut').textContent=C.duration.value+' weeks';$('#boneOut').textContent=C.bone.value+'%';$('#brainOut').textContent=C.brain.value+'%';$('#persistOut').textContent=C.persist.value+'%';$('#iodineOut').textContent=C.iodine.value+'%';$('#multiOut').textContent=C.multi.value+'%';$('#genOut').textContent=C.generations.value;$('#modelNote').textContent=x.note;$('#femur').textContent=x.fem.toFixed(1);$('#icv').textContent=x.icv.toFixed(0);$('#distance').textContent=x.d.toFixed(2);$('#distanceBig').textContent=x.d.toFixed(2);$('#state').textContent=x.S.toFixed(2);$('#suscept').textContent=x.sus.toFixed(2)+'×';$('#iodineState').textContent=x.thyroid.toFixed(2);let fit=x.d<2?'Very close':x.d<5?'Close region':x.d<20?'Relatively close':x.d<70?'Moderate mismatch':'Large mismatch';$('#fitLabel').textContent=fit;let end=Math.min(40,x.st+x.du);$('#windowText').textContent=x.st+' → '+end+' weeks';$('#window').style.left=(x.st/40*100)+'%';$('#window').style.width=((end-x.st)/40*100)+'%';visibility();draw(x)}
Object.values(C).forEach(e=>e.addEventListener('input',update));
$('#pCombined').onclick=()=>{C.family.value='combined';C.severity.value=78;C.start.value=10;C.duration.value=16;C.bone.value=88;C.brain.value=88;C.persist.value=88;C.iodine.value=82;C.multi.value=65;C.generations.value=4;update()};
$('#pIodine').onclick=()=>{C.family.value='iodine';C.severity.value=80;C.start.value=8;C.duration.value=14;C.bone.value=25;C.brain.value=85;C.persist.value=85;C.iodine.value=85;C.multi.value=10;C.generations.value=3;update()};
$('#pIGF').onclick=()=>{C.family.value='igf';C.severity.value=70;C.start.value=18;C.duration.value=12;C.bone.value=85;C.brain.value=55;C.persist.value=80;C.iodine.value=20;C.multi.value=20;C.generations.value=3;update()};
update();